name: Daily Commit

on:
  schedule:
    - cron: '56 23 * * *'  # Runs daily at 23:56 UTC
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # ✅ Grants write access to push commits

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Change
        run: echo "$(date)" > daily_update.txt

      - name: Commit and Push (your-email@example.com)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "your-email@example.com"
          git add daily_update.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Uses built-in GitHub authentication
